SELECT TABLA.COD_FUNC, TABLA.TIPO, TABLA.CODIGO_BACKUP, FU.NombC AS NOMBRE_BACKUP
FROM (SELECT C.COD_FUNC, QUIEN_ES_SU_BACKUP.CODIGO_BACKUP, QUIEN_ES_SU_BACKUP.TIPO
FROM dbo.COLABORADOR_BASICOS AS C 
INNER JOIN(
    SELECT FuCod AS COD_FUNC, BSKFUCOD AS CODIGO_BACKUP, 1 AS TIPO FROM dbo.FUNCIONARI WHERE (BSKFUCOD > 0) AND FEst = 'A'
    UNION ALL SELECT FuCod, BSKFUCOD2, 1 AS Expr1 FROM dbo.FUNCIONARI WHERE BSKFUCOD2 > 0 AND FEst = 'A'
    UNION ALL SELECT FuCod, BSKFUCOD3, 1 AS Expr1 FROM dbo.FUNCIONARI WHERE BSKFUCOD3 > 0 AND FEst = 'A'
    UNION ALL SELECT FuCod, BSKFUCOD4, 1 AS Expr1 FROM dbo.FUNCIONARI WHERE BSKFUCOD4 > 0 AND FEst = 'A' AND BSKFUCOD4 <> FuCod
) AS QUIEN_ES_SU_BACKUP ON QUIEN_ES_SU_BACKUP.COD_FUNC = C.COD_FUNC
UNION ALL SELECT C.COD_FUNC, BACKUP_DE_QUIEN_ES.CODIGO_BACKUP, BACKUP_DE_QUIEN_ES.TIPO FROM dbo.COLABORADOR_BASICOS AS C
INNER JOIN (
    SELECT BSKFUCOD, BSKFUCOD2, BSKFUCOD3, FuCod AS CODIGO_BACKUP, 2 AS TIPO FROM dbo.FUNCIONARI WHERE (BSKFUCOD > 0 OR BSKFUCOD2 > 0 OR BSKFUCOD3 > 0) AND FEst = 'A'
) AS BACKUP_DE_QUIEN_ES ON C.COD_FUNC IN (BACKUP_DE_QUIEN_ES.BSKFUCOD, BACKUP_DE_QUIEN_ES.BSKFUCOD2, BACKUP_DE_QUIEN_ES.BSKFUCOD3)) AS TABLA 
INNER JOIN dbo.FUNCIONARI AS FU ON FU.FuCod = TABLA.CODIGO_BACKUP AND FU.FEst = 'A'



--VISTA COLABORADOR_FALTAS_EVENTOS
SELECT COD_FUNC, COD_FALTA, DESC_FALTA, MES, ANHO, 
CASE WHEN MES <> '' AND ANHO > 0 THEN COUNT(*) ELSE 0 END AS TOTAL_CONCEPTO, 
CASE WHEN DESC_FALTA LIKE '%INJUS%' THEN 'ROJO' WHEN DESC_FALTA LIKE '%JUS%' THEN 'VERDE' ELSE 'AZUL' END AS COLOR
FROM (SELECT F.FuCod AS COD_FUNC, FALTAS.CODJUS AS COD_FALTA, FALTAS.DESJUS AS DESC_FALTA, 
    CASE WHEN TABMUSU IS NOT NULL THEN MONTH(TabMFecha) ELSE '' END AS MES, 
    CASE WHEN TABMUSU IS NOT NULL THEN YEAR(TabMFecha) ELSE '' END AS ANHO
    FROM dbo.FUNCIONARI AS F
    LEFT OUTER JOIN dbo.FSD050 AS F50 ON F.FuCod = F50.FuCod 
    LEFT OUTER JOIN 
        (
            SELECT 'AI' AS CODJUS, 'Ausencia Injustificada' AS DESJUS
            UNION ALL SELECT 'AJ' AS Expr1, 'Ausencia Justificada' AS Expr2
            UNION ALL SELECT 'TI' AS Expr1, 'Tardia Injustificada' AS Expr2
            UNION ALL SELECT 'TJ' AS Expr1, 'Tardia Justificada' AS Expr2
            UNION ALL SELECT 'SI' AS Expr1, 'Salida Antes de Horario Injustificado' AS Expr2
            UNION ALL SELECT 'SJ' AS Expr1, 'Salida Antes de Horario Justificado' AS Expr2
            UNION ALL SELECT 'HAEI' AS Expr1, 'Horario de Almuerzo Extendido Injustificado' AS Expr2
            UNION ALL SELECT 'HAEJ' AS Expr1, 'Horario de Almuerzo Extendido Justificado' AS Expr2
            UNION ALL SELECT 'OMEI' AS Expr1, 'Omisión de Marcación de Entrada Injustificada' AS Expr2
            UNION ALL SELECT 'OMEJ' AS Expr1, 'Omisión de Marcación de Entrada Justificada' AS Expr2
            UNION ALL SELECT 'OMSI' AS Expr1, 'Omisión de Marcación de Salida Injustificada' AS Expr2
            UNION ALL SELECT 'OMSJ' AS Expr1, 'Omisión de Marcación de Salida Justificada' AS Expr2
            UNION ALL SELECT 'OMSAI' AS Expr1, 'Omisión de Marcación de Salida Almuerzo Injustificado' AS Expr2
            UNION ALL SELECT 'OMSAJ' AS Expr1, 'Omisión de Marcación de Salida Almuerzo Justificado' AS Expr2
            UNION ALL SELECT 'OMEAI' AS Expr1, 'Omisión de Marcación de Entrada Almuerzo Injustificado' AS Expr2
            UNION ALL SELECT 'OMEAJ' AS Expr1, 'Omisión de Marcación de Entrada de Almuerzo Justificado' AS Expr2
            UNION ALL SELECT 'V' AS Expr1, 'Vacaciones' AS Expr2
            UNION ALL SELECT 'R' AS Expr1, 'Reposo' AS Expr2
            UNION ALL SELECT 'PE' AS Expr1, 'Permiso Especial' AS Expr2
        ) 
        AS FALTAS ON 1 = 1
    LEFT OUTER JOIN dbo.RRHH121 AS R ON FALTAS.CODJUS = R.TabMTipJ AND F50.ClUsu = R.TABMUSU
    WHERE (F.FEst = 'A') AND (F.FMrcSN = 'S')) AS TABLA
WHERE (MES <> '') AND (ANHO > 0)
GROUP BY COD_FUNC, COD_FALTA, DESC_FALTA, MES, ANHO


--VISTA COLABORADOR_SALARIO
SELECT 
A_1.COD_FUNC AS COD_FUNC, 
CONVERT(DATE, '01/' + CONVERT(VARCHAR (20), B_1.MES) + '/' + CONVERT(VARCHAR(20), B_1.ANHO)) AS PERIODO,
CASE 
        WHEN B_1.MES = 1 THEN 'ENERO' 
        WHEN B_1.MES = 2 THEN 'FEBRERO' 
        WHEN B_1.MES = 3 THEN 'MARZO' 
        WHEN B_1.MES = 4 THEN 'ABRIL' 
        WHEN B_1.MES = 5 THEN 'MAYO' 
        WHEN B_1.MES = 6 THEN 'JUNIO' 
        WHEN B_1.MES = 7 THEN 'JULIO' 
        WHEN B_1.MES = 8 THEN 'AGOSTO' 
        WHEN B_1.MES = 9 THEN 'SEPTIEMBRE' 
        WHEN B_1.MES = 10 THEN 'OCTUBRE' 
        WHEN B_1.MES = 11 THEN 'NOVEMBRE' 
        WHEN B_1.MES = 12 THEN 'DICIEMBRE'
    END AS MES,
B_1.ANHO AS AÑO,
ISNULL(C_1.MONTO_COBRADO_SAL_FIJO, 0) AS SALARIO_BRUTO_FIJO,
(ISNULL(C_2.MONTO_COBRADO_SAL_VARIABLE, 0) + ISNULL(C_3.MONTO_COBRADO_SAL_MANUAL, 0)) AS SALARIO_BRUTO_VARIABLE,
(ISNULL(C_1.MONTO_COBRADO_SAL_FIJO, 0) + ISNULL(C_2.MONTO_COBRADO_SAL_VARIABLE, 0) + ISNULL(C_3.MONTO_COBRADO_SAL_MANUAL, 0)) AS TOTAL,
ROUND(((ISNULL(C_1.MONTO_COBRADO_SAL_FIJO, 0) + ISNULL(C_2.MONTO_COBRADO_SAL_VARIABLE, 0) + ISNULL(C_3.MONTO_COBRADO_SAL_MANUAL, 0)) / 12), 0) AS AGUINALDO,
CASE 
	WHEN D_1.REGIMEN_CODIGO = 2 THEN ROUND((((ISNULL(C_1.MONTO_COBRADO_SAL_FIJO, 0) + ISNULL(C_2.MONTO_COBRADO_SAL_VARIABLE, 0) + ISNULL(C_3.MONTO_COBRADO_SAL_MANUAL, 0)) * 25.5) / 100), 0) 
	WHEN D_1.REGIMEN_CODIGO = 20 THEN 0
END AS APORTE_PATRONAL,
A_1.ESTADO AS ESTADO

FROM (SELECT A.FuCIC AS NRO_CI, A.FEst AS ESTADO, A.FuCod AS COD_FUNC, A.NombC AS NOMBRE_COLABORADOR, B.ChNom AS GERENCIA, C.AreDesc AS DEPARTAMENTO, D.CjNom AS CARGO, A.FuFchIng AS FECHA_INGRESO, A.FuFEgres AS FECHA_EGRESO, FuRegi AS REGIMEN
    FROM dbo.FUNCIONARI AS A     
    INNER JOIN dbo.FST051 AS B ON A.ChDpto = B.ChDpto AND A.ChDpto = B.ChDpto 
    INNER JOIN dbo.AREA AS C ON A.AreCod = C.AreCod AND A.ChDpto = C.ChDpto AND A.AreaCodigo = C.AreaCodigo AND A.DivCodigo = C.DivCodigo 
    INNER JOIN dbo.FST053 AS D ON A.CjCar = D.CjCar
    WHERE (A.FEst = 'A')) AS A_1 

INNER JOIN (SELECT YEAR(A.FuncFecHas) AS ANHO, MONTH(FuncFecHas) AS MES, A.FuCod AS FUNC_COD
    FROM dbo.CPTOFUNC AS A 
    WHERE (A.FuncCredTo > 0) AND (A.RR01Id IN (1, 2, 6))
    GROUP BY YEAR(A.FuncFecHas), MONTH(FuncFecHas), A.FuCod) AS B_1 ON A_1.COD_FUNC = B_1.FUNC_COD

INNER JOIN (SELECT YEAR(A.FuncFecHas) AS ANHO, MONTH(A.FuncFecHas) AS MES, A.FuCod AS FUNC_COD, A.CptoCod AS REGIMEN_CODIGO 
	FROM CPTOFUNC1 A
	WHERE A.CptoCod IN (2, 20)
	GROUP BY YEAR(A.FuncFecHas), MONTH(FuncFecHas), A.FuCod, A.CptoCod) AS D_1 ON A_1.COD_FUNC = D_1.FUNC_COD AND B_1.ANHO = D_1.ANHO AND B_1.MES = D_1.MES

LEFT OUTER JOIN (
    SELECT YEAR(A.FuncFecHas) AS ANHO, MONTH(A.FuncFecHas) AS MES, A.FuCod, A.FuncFecHas AS FECHA_CORTE, B.RR01Id AS TIPO_LIQ_COD_SAL_FIJO, B.RR01Des AS TIPO_LIQ_DESC_SAL_FIJO, CAST(A.FuncCredTo AS numeric) AS MONTO_COBRADO_SAL_FIJO
    FROM dbo.CPTOFUNC AS A
    INNER JOIN dbo.RRHH01 AS B ON A.RR01Id = B.RR01Id AND B.RR01Id = 1
    WHERE (A.FuncCredTo > 0)) AS C_1 ON B_1.FUNC_COD = C_1.FuCod AND B_1.ANHO = C_1.ANHO AND B_1.MES = C_1.MES

LEFT OUTER JOIN (
    SELECT YEAR(A.FuncFecHas) AS ANHO, MONTH(A.FuncFecHas) AS MES, A.FuCod, A.FuncFecHas AS FECHA_CORTE, B.RR01Id AS TIPO_LIQ_COD_SAL_VARIABLE, B.RR01Des AS TIPO_LIQ_DESC_SAL_VARIABLE, CAST(A.FuncCredTo AS numeric) AS MONTO_COBRADO_SAL_VARIABLE
    FROM dbo.CPTOFUNC AS A
    INNER JOIN dbo.RRHH01 AS B ON A.RR01Id = B.RR01Id AND B.RR01Id = 2
    WHERE (A.FuncCredTo > 0)) AS C_2 ON B_1.FUNC_COD = C_2.FuCod AND B_1.ANHO = C_2.ANHO AND B_1.MES = C_2.MES

LEFT OUTER JOIN (
    SELECT YEAR(A.FuncFecHas) AS ANHO, MONTH(A.FuncFecHas) AS MES, A.FuCod, A.FuncFecHas AS FECHA_CORTE, B.RR01Id AS TIPO_LIQ_COD_SAL_MANUAL, B.RR01Des AS TIPO_LIQ_DESC_SAL_MANUAL, CAST(A.FuncCredTo AS numeric) AS MONTO_COBRADO_SAL_MANUAL
    FROM dbo.CPTOFUNC AS A
    INNER JOIN dbo.RRHH01 AS B ON A.RR01Id = B.RR01Id AND B.RR01Id = 6
    WHERE (A.FuncCredTo > 0)) AS C_3 ON B_1.FUNC_COD = C_3.FuCod AND B_1.ANHO = C_3.ANHO AND B_1.MES = C_3.MES